-- primary file for reading in data objects
--      example: 100_data_exp.txt

function read_data_file(file_name)
  local file = io.open(file_name, "r")
  if file == nil then
    blight.output("Error: could not open file: " .. file_name)
    return nil
  end
  local data = file:read("*all")
  file:close()
  return data
end

-- TODO: need to fix this function was just generated by co-pilot
function data_file_to_lookup_table(file_name, lookup_column, output_table, separator)
  local data = read_data_file(file_name)
  if data == nil then
    return nil
  end
  local lines = {}
  for line in data:gmatch("[^\r\n]+") do
    table.insert(lines, line)
  end
  local header = lines[1]
  local header_parts = {}
  for part in header:gmatch("[^"..separator.."]+") do
    table.insert(header_parts, part:lower())
  end
  local lookup_index = nil
  for i, part in ipairs(header_parts) do
    if part:lower() == lookup_column then
      lookup_index = i
    end
  end
  if lookup_index == nil then
    blight.output("Error: could not find lookup column: " .. lookup_column)
    return nil
  end
  local output_table = {}
  for i = 2, #lines do
    local line = lines[i]
    local parts = {}
    for part in line:gmatch("[^"..separator.."]+") do
      if IS_INT(part) then
        part = tonumber(part)
        table.insert(parts, part)
      end
    end
    output_table[parts[lookup_index]] = parts
  end
end

data_file_to_lookup_table('~/.config/blightmud/swmud/100_data_exp.txt', "lvl", EXP_TABLE, "|")